import type { Metadata } from "next";
import { Lora, Carlito } from "next/font/google";
import "./globals.css";

const lora = Lora({
  subsets: ["latin", "cyrillic"],
  variable: "--font-lora",
  weight: ["400", "700"],
});

const carlito = Carlito({
  subsets: ["latin", "cyrillic"],
  variable: "--font-carlito",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${lora.variable} ${carlito.variable}`}>{children}</body>
    </html>
  );
}
